version: "3.8"

services:
  beid-mw:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: beid-mw
    restart: unless-stopped
    network_mode: "host" # Use host network for simplicity
    # Alternate configuration if host network is problematic
    # ports:
    #   - "8080:8080"
    volumes:
      - ..:/app # Mount the entire application directory
      - /dev/bus/usb:/dev/bus/usb # USB devices
      - /run/pcscd:/run/pcscd # PCSCD socket
      - /var/run/pcscd:/var/run/pcscd # Alternative PCSCD socket location
    # Add direct device access - more comprehensive approach
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/pcscd:/dev/pcscd
    # Either give privileged access or specific capabilities
    privileged: true
    # cap_add:
    #   - SYS_ADMIN
    #   - NET_ADMIN
    environment:
      - PYKCS11LIB=/usr/lib/x86_64-linux-gnu/libbeidpkcs11.so.0
      - PYTHONPATH=/app
      - USE_HOST_PCSCD=true
    # Make sure the container can access the host udev
    group_add:
      - "108" # Typically the ID of plugdev group, may need adjustment for your system
